# Generated by Django 4.1.7 on 2023-04-01 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100, unique=True)),
                ("price", models.FloatField()),
                ("season", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="last_transaction",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("order_status", models.CharField(max_length=100)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("client_id", "order_date")},
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "item_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="basket.product"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="basket.order"
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "item_name")},
            },
        ),
    ]
