# Generated by Django 4.1.7 on 2023-04-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0002_product_alter_user_last_transaction_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_transaction",
            field=models.DateField(blank=True, null=True),
        ),
    ]
