# Generated by Django 4.1.7 on 2023-04-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0003_alter_user_last_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_status",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
