# Generated by Django 4.1.7 on 2023-04-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0005_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="order",
            unique_together=set(),
        ),
    ]
