# Generated by Django 4.1.7 on 2023-04-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0007_alter_order_order_date_alter_order_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="season",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
