# Generated by Django 4.1.7 on 2023-04-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0009_coupon_redemption"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociationRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consequent", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("antecedents", models.CharField(max_length=100)),
                ("confidence", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="MarketBasketCharts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chart_name", models.CharField(max_length=100)),
                ("chart_created_at", models.DateTimeField(auto_now_add=True)),
                ("chart_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chart_image",
                    models.ImageField(blank=True, null=True, upload_to="charts/"),
                ),
            ],
        ),
    ]
