# Generated by Django 4.1.7 on 2023-04-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0010_associationrules_marketbasketcharts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associationrules",
            name="antecedents",
            field=models.JSONField(max_length=100),
        ),
        migrations.AlterField(
            model_name="associationrules",
            name="consequent",
            field=models.JSONField(),
        ),
    ]
