# Generated by Django 4.1.7 on 2023-04-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0011_alter_associationrules_antecedents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFMTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfm_segment", models.CharField(max_length=100, unique=True)),
                ("recency", models.FloatField()),
                ("frequency", models.FloatField()),
                ("monetary", models.FloatField()),
            ],
        ),
    ]
